console.log("SERVER START");
require('dotenv').config();
const app = require('./app');
require('./database/db');
const { runMigrations } = require('./database/migrate');
runMigrations();
const { startSyncLoop } = require('./services/oneDriveSync');
startSyncLoop();
const PORT = process.env.PORT || 5000;
app.listen(PORT, '0.0.0.0', () => { console.log("SERVER RUNNING ON PORT " + PORT); });
